### ISSUE TITLE
Icon font regression when using Vite

### ISSUE THREAD

**Issue by cernyjakub** [twbs/icons#1381]
Hello!

I have been using icon font in Vite by simpley including 1 line in my SCSS file:

`@import 'bootstrap-icons/font/bootstrap-icons';`

After updating to 1.9, this is no longer working. I assume it is related to changes of font-path variables, hashes, etc. - as mentioned in #1378.

It would be super-cool to keep this compatibility.

**Comment by cernyjakub** [comment]
Very likely, this is related to https://github.com/vitejs/vite/issues/7651 - Vite SASS processor is unable to peoperly rebase `url()` when there are variables in it (if I understand correctly).

So move from (1.8.3):

```
$bootstrap-icons-font-src: url("./fonts/bootstrap-icons.woff2?08efbba7c53d8c5413793eecb19b20bb") format("woff2"),
url("./fonts/bootstrap-icons.woff?08efbba7c53d8c5413793eecb19b20bb") format("woff") !default;
```

to (1.9)

```
$bootstrap-icons-font-src: url("#{$bootstrap-icons-font-file}.woff2?#{$bootstrap-icons-font-hash}") format("woff2"), url("#{$bo
otstrap-icons-font-file}.woff?#{$bootstrap-icons-font-hash}") format("woff") !default;
```

killed the Vite importer.

As a workaround, we can import the generated CSS like this:

```
@import 'bootstrap-icons/font/bootstrap-icons.css';
```
It skips SASS and in plain CSS the `url()` rebasing apparently works...

**Comment by tyqualters** [comment]
Can confirm this is still an issue regarding the latest versions. Using Vite and SASS, `@import "~bootstrap-icons/font/bootstrap-icons";` which includes the SASS version, does in fact break. Workaround as mentioned, `@import "~bootstrap-icons/font/bootstrap-icons.css";` does fix the issue.

**Comment by mdo** [comment]
Any idea what the Vite Sass compiler is doing that's different than the usual Sass compilation? We're not seeing any build errors on our end.

**Comment by nCrazed** [comment]
parcel.js is failing in similar way too: https://github.com/parcel-bundler/parcel/issues/6285

**Comment by XhmikosR** [comment]
This should be fixed in main and will be in v1.10.4.

**Comment by cernyjakub** [comment]
I am still seeing the same erratic behavior, even after upgrading to 1.10.5

**Comment by XhmikosR** [comment]
Yeah, nothing changed from our side. I still haven't had the chance to finish the CI job, but chances are the  changes will be the same. I haven't pinpointed the root cause.

**Comment by andymerskin** [comment]
I know this is old, so not meaning to necro, but Vite 4.x changed the default charset to UTF-8 and recommends people ensure they're using the correct `Content-Type` header when serving CSS, as well as having your `index.html` include the `<meta charset="utf-8 />` tag in your `<head>`, which should be default for Vite users anyway.

Thread: https://github.com/vitejs/vite/issues/13676#issuecomment-1612688039

**Comment by CatchABus** [comment]
> This should be fixed in main and will be in v1.10.4.

I think this issue should be re-opened as the problem still persists.

**Comment by oussama-he** [comment]
I'm using version `1.11.2` with `vite 4.4.11` and I have tried the workaround mentioned by @cernyjakub and @tyqualters and the issue persists.

I get this error in the console:

![image](https://github.com/twbs/icons/assets/18425315/bd1fa9d1-7629-47c7-9e6e-688a09e26e6a)

And this error in the server (Django server, vite server doesn't log anything):

![image](https://github.com/twbs/icons/assets/18425315/7527d47e-d31d-4b86-91fe-3761543bf6a6)

Is there any news about this bug or other workarounds?

**Comment by jhjvandenbroek** [comment]
I use the workaround given by @cernyjakub and @tyqualters which is to include the plain css instead of the sass version.

I describe the same workaround in my blog [How to Install Bootstrap in Laravel With Vite](https://laracoding.com/how-to-install-bootstrap-in-laravel-with-vite-tutorial/)

This is far from ideal, I'd prefer to be able to use the sass version.

**Comment by oussama-he** [comment]
@jhjvandenbroek do you use the same versions (`bootstrap-icons 1.11.2` and `vite 4.4.11`)?
The workaround doesn't work for me.

**Comment by jrd-lewis** [comment]
Still an issue with vite 5.0 and bootstrap-icons 1.11.3; but the workaround of using the compiled css still works in the interim.

**Comment by lucasalvesa** [comment]
Does anyone have a different solution or workaround to this very same problem?

**Comment by aaw20904** [comment]
I have  the same problem with  "bootstrap-icons.min" file. I wrote direct path, but I had no success: "Internal server error: Failed to resolve import "D:/web-work/vite_react_lrn/node_modules/bootstrap-icons/font/fonts/bootstrap-icons.min.css" from "src/App.jsx". Does the file exist?". I decided to export only font in a .css file :  @font-face{
   font-display: swap;
  font-family: 'Icons';
   font-style: normal;
  font-weight: 400;
  src: url('../node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2') format('woff2'); 
}  
It works! To insert icon I insert  codes :
  <i>&#xF799;</i> 
and styling in .CSS the <i> tag: color, font-size e.t.c.

**Comment by jeremy0519** [comment]
I suppose even adding `@import 'bootstrap-icons/font/bootstrap-icons.css';` should be covered in the [official usage documentation](https://icons.getbootstrap.com/#usage) for people using Vite.

**Comment by sourabhkahar** [comment]
> I know this is old, so not meaning to necro, but Vite 4.x changed the default charset to UTF-8 and recommends people ensure they're using the correct `Content-Type` header when serving CSS, as well as having your `index.html` include the `<meta charset="utf-8 />` tag in your `<head>`, which should be default for Vite users anyway.
> 
> Thread: [vitejs/vite#13676 (comment)](https://github.com/vitejs/vite/issues/13676#issuecomment-161268803
thanks ! helped me a lot.

**Comment by mdo** [comment]
I'm very late to this, but this looks like the ideal solution:

```scss
$bootstrap-icons-font-dir: "bootstrap-icons/font/fonts";
@import "bootstrap-icons/font/bootstrap-icons.scss";
```

Example at https://stackblitz.com/edit/github-srcdebe8?file=package.json,src%2Fscss%2Fstyles.scss,src%2Findex.html%3AL7,src%2Fscss%2Ficons.scss

I can swing back around at some point to improve the usage docs for stuff like Vite.
