### ISSUE TITLE
Icon font documentation example broken

### ISSUE THREAD

**Issue by catchmyfame** [twbs/icons#1412]
Under the Usage section of the icon documentation, https://icons.getbootstrap.com/#usage, the icon fonts section examples are broken and incorrect. Aside from neither of the examples being displayed, the documentation uses the example of `class="bi-alarm"`, yet the icons themselves all seem to also require the `bi` class, e.g. `class="bi bi-alarm"`. However, even when I add the `bi` class using my developer tools, nothing appears (maybe at that point it's too late).

**Comment by sinjuangajan** [comment]
![image](https://user-images.githubusercontent.com/4011140/186060419-a21e01e5-bcd4-4bc5-a6e2-5cafa64cf03f.png)

**Comment by mdo** [comment]
Fixed with the update in #706.

**Comment by catchmyfame** [comment]
@mdo I'm not seeing this fixed on getbootstrap.com; the issue is still there. Is the fix not live yet?

**Comment by mdo** [comment]
It is not. Everything requires a release, hoping for this week or next.
