### ISSUE TITLE
Icon font not visible

### ISSUE THREAD

**Issue by iconmaster5326** [twbs/icons#1442]
Everywhere you can use Bootstrap icons via the icon font, they are not showing up. Do note that they show up by other means (like `img` and `svg`).

![image](https://user-images.githubusercontent.com/3768458/192149274-f7f58817-77c6-4ec6-80d6-fe507544b85c.png)

I am using Windows 10 , and this was tested on Chrome 105.0.5195.127 and Firefox 105.0.1.

**Comment by jankapunkt** [comment]
I can confirm this on Ubuntu 22.04 with same FF version and Chromium 105.0.5195.125
I also can't get any icons to work when installed this package from NPM, for example when importing `bootstrap-icons/font/bootstrap-icons.css` I will get in Firefox after bundling:

```
08:13:57.532 downloadable font: rejected by sanitizer (font-family: "bootstrap-icons" style:normal weight:400 stretch:100 src index:0) source: http://localhost:3000/fonts/bootstrap-icons.woff2?8d200481aa7f02a2d63a331fc782cfaf
08:13:57.574 downloadable font: rejected by sanitizer (font-family: "bootstrap-icons" style:normal weight:400 stretch:100 src index:1) source: http://localhost:3000/fonts/bootstrap-icons.woff?8d200481aa7f02a2d63a331fc782cfaf 
```

on Chromium I get

```
Failed to decode downloaded font: <URL>
6OTS parsing error: invalid sfntVersion: 1008813135
localhost/:1 OTS parsing error: invalid sfntVersion: 1008813135
localhost/:1 OTS parsing error: invalid sfntVersion: 1008813135
localhost/:1 OTS parsing error: invalid sfntVersion: 1008813135
localhost/:1 OTS parsing error: invalid sfntVersion: 1008813135
localhost/:1 OTS parsing error: invalid sfntVersion: 1008813135
localhost/:1 OTS parsing error: invalid sfntVersion: 1008813135
```

Seems like corrupted font files to :thinking:

**Comment by mdo** [comment]
Should be fixed now

**Comment by nitinprojects** [comment]
I see it's still not working.

Please refer  - https://codesandbox.io/s/friendly-water-f7zxsl?file=/src/App.js

**Comment by benmcm1994** [comment]
Still not working

**Comment by nitinprojects** [comment]
for now it can be fixed by downloading  fonts https://github.com/twbs/icons/tree/main/font/fonts and loading them on you web page using @font-face.

<pre><code>@font-face {
  font-family: bootstrapIcon;
  src:  url('bootstrap-icons.woff2') format('woff2'),
        url(bootstrap-icons.woff') format('woff');
}</code></pre>

<pre><code> .bi::before,
[class^="bi-"]::before,
[class*=" bi-"]::before {
  font-family: bootstrapIcon !important;
}
</code></pre>

**Comment by 1GR3** [comment]
It is still showing squares for me, while it seems to work fine when loaded from CDN.
