### ISSUE TITLE
Show icons with same tags on icon page

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/icons#473]
Example on the page: https://icons.getbootstrap.com/icons/arrow-right-square-fill/
Show a header called "More icons" or something with right arrow not filled, left arrow, etc.

Like Font Awesome does:
https://fontawesome.com/icons/database?style=solid
When you scroll down it says "More Computers Icons".

**Comment by mdo** [comment]
Would love that! I'd also love to do category pages and more to help lessen the page load on the homepage.

**Comment by XhmikosR** [comment]
This is fixed in 1.10.4. We went with `q=brand`. We can change the query param to something else since I agree, it's not very self-explanatory. Suggestions welcome.

**Comment by XhmikosR** [comment]
It's not quite the same thing, and we plan to try to add taxonomies in the next version. Feel free to make a new issue if there isn't one.

**Comment by vanillajonathan** [comment]
Sounds good.

The Bootstrap Icons page still doesn't show related icons on the page for the icon though, only when searching.
The original post describes it in another way where each icon page also shows related icons.

**Comment by XhmikosR** [comment]
It should be doable, PRs welcome :)

See how we do it in the blog: https://github.com/twbs/blog/blob/88064273438957c08a932d54bcdc47058135d2ba/src/layouts/posts/single.html#L21-L39

**Comment by vanillajonathan** [comment]
Thanks, I filed a PR by looking at the two code snippets you provided.

**Comment by XhmikosR** [comment]
It's not enough, though 😛

You need to take care of the layout too.
